# 身份验证是否允许所有人可用
all: false
# 网站信息获取是否允许所有人可用
WZXXALL: true
# 端口扫描是否允许所有人可用
DKSMALL: false
# Whois域名查询是否允许所有人可用
WSYMALL: false
# 全球IP信息查询是否允许所有人可用
IPCXALL: true
# 网站测速是否允许所有人可用
WZCSALL: true
# 二维码生成是否允许所有人可用
SRWMALL: true
# 抖音视频解析是否允许所有人可用
DYJXALL: true