# 身份验证是否允许所有人可用
all: false
# 网站信息获取是否允许所有人可用
all: true
# Ping是否允许所有人可用
all: true
# Sping是否允许所有人可用
all: true
# 端口扫描是否允许所有人可用
all: false
# Whois域名查询是否允许所有人可用
all: false
# 全球IP信息查询是否允许所有人可用
all: true
# 网站测速是否允许所有人可用
all: true
# 二维码生成是否允许所有人可用
all: true
# 抖音视频解析是否允许所有人可用
all: true